// Curated recipe catalog for the Recipes browser in the calories tracker.
// Nutrition values are PER SERVING estimates. Card/hero photos are looked up
// at runtime by name via /api/food-photo (Pexels), so recipes ship no assets.

export type Recipe = {
  id: string;
  title: string;
  // Primary browse row on the recipes screen. Must be one of RECIPE_CATEGORIES.
  category: string;
  // Chips on the detail screen, e.g. meal slot and dietary notes.
  tags: string[];
  serves: number;
  kcal: number;
  protein: number;
  carbs: number;
  fats: number;
  // Overrides the stock-photo search term when the title alone matches poorly.
  photoQuery?: string;
  ingredients: string[];
  directions: string[];
};

export const RECIPE_CATEGORIES = [
  "Mediterranean",
  "High Protein",
  "High Fiber",
  "Plant-Based",
  "Pre-Workout",
  "Post-Workout",
] as const;

export const RECIPES: Recipe[] = [
  // ---------------------------------------------------------------- Mediterranean
  {
    id: "med-greek-chicken-bowl",
    title: "Greek Chicken Grain Bowl",
    category: "Mediterranean",
    tags: ["Lunch", "Under 500 Calories", "High Protein"],
    serves: 2,
    kcal: 470,
    protein: 38,
    carbs: 42,
    fats: 16,
    photoQuery: "greek chicken bowl quinoa",
    ingredients: [
      "2 chicken breasts (about 300 g), cubed",
      "1 cup cooked quinoa",
      "1 cup cherry tomatoes, halved",
      "1/2 cucumber, diced",
      "1/4 red onion, thinly sliced",
      "40 g feta cheese, crumbled",
      "8 kalamata olives",
      "1 tbsp olive oil",
      "1 tsp dried oregano",
      "Juice of 1/2 lemon",
    ],
    directions: [
      "Season the cubed chicken with oregano, salt, and pepper.",
      "Heat the olive oil in a pan over medium-high heat and cook the chicken for 6 to 8 minutes until golden and cooked through.",
      "Divide the quinoa between two bowls and top with tomatoes, cucumber, red onion, olives, and feta.",
      "Add the chicken, squeeze the lemon over everything, and serve warm.",
    ],
  },
  {
    id: "med-salmon-couscous",
    title: "Lemon Salmon with Herbed Couscous",
    category: "Mediterranean",
    tags: ["Dinner", "Omega-3", "Under 500 Calories"],
    serves: 2,
    kcal: 490,
    protein: 34,
    carbs: 40,
    fats: 20,
    photoQuery: "grilled salmon couscous lemon",
    ingredients: [
      "2 salmon fillets (about 140 g each)",
      "3/4 cup dry couscous",
      "1 cup low-sodium chicken or vegetable broth",
      "1 tbsp olive oil",
      "1 lemon, half juiced and half sliced",
      "2 tbsp fresh parsley, chopped",
      "1 garlic clove, minced",
      "Salt and black pepper to taste",
    ],
    directions: [
      "Preheat the oven to 200C (400F). Place the salmon on a lined tray, top with lemon slices, salt, and pepper, and bake for 12 to 14 minutes.",
      "Bring the broth to a boil, pour it over the couscous, cover, and let stand for 5 minutes.",
      "Fluff the couscous with a fork and stir in the olive oil, garlic, parsley, and lemon juice.",
      "Serve the salmon over the herbed couscous.",
    ],
  },
  {
    id: "med-chickpea-salad",
    title: "Chopped Chickpea Village Salad",
    category: "Mediterranean",
    tags: ["Lunch", "Vegetarian", "High Fiber", "Under 500 Calories"],
    serves: 2,
    kcal: 380,
    protein: 14,
    carbs: 38,
    fats: 20,
    photoQuery: "chickpea greek salad feta",
    ingredients: [
      "1 can (400 g) chickpeas, drained and rinsed",
      "1 cup cherry tomatoes, quartered",
      "1 cucumber, chopped",
      "1/2 green bell pepper, chopped",
      "1/4 red onion, finely sliced",
      "50 g feta cheese, cubed",
      "10 kalamata olives",
      "1.5 tbsp extra virgin olive oil",
      "1 tbsp red wine vinegar",
      "1 tsp dried oregano",
    ],
    directions: [
      "Combine the chickpeas, tomatoes, cucumber, pepper, onion, and olives in a large bowl.",
      "Whisk the olive oil, vinegar, oregano, and a pinch of salt into a dressing.",
      "Toss the salad with the dressing and top with the feta.",
      "Let it sit for 10 minutes before serving so the flavors come together.",
    ],
  },
  {
    id: "med-shakshuka",
    title: "Classic Shakshuka",
    category: "Mediterranean",
    tags: ["Breakfast", "Vegetarian", "Under 500 Calories"],
    serves: 2,
    kcal: 340,
    protein: 18,
    carbs: 22,
    fats: 20,
    photoQuery: "shakshuka eggs tomato skillet",
    ingredients: [
      "4 large eggs",
      "1 can (400 g) crushed tomatoes",
      "1 red bell pepper, sliced",
      "1/2 onion, diced",
      "2 garlic cloves, minced",
      "1 tbsp olive oil",
      "1 tsp smoked paprika",
      "1/2 tsp ground cumin",
      "Fresh parsley and crumbled feta to finish",
    ],
    directions: [
      "Heat the olive oil in a skillet over medium heat and soften the onion and pepper for 5 minutes.",
      "Stir in the garlic, paprika, and cumin and cook for 1 minute.",
      "Pour in the crushed tomatoes, season, and simmer for 8 minutes until slightly thickened.",
      "Make four wells in the sauce and crack an egg into each. Cover and cook 5 to 7 minutes until the whites are set.",
      "Finish with parsley and a little feta, and serve with warm bread if you like.",
    ],
  },

  // ---------------------------------------------------------------- High Protein
  {
    id: "hp-turkey-rice-skillet",
    title: "Ground Turkey Burrito Skillet",
    category: "High Protein",
    tags: ["Dinner", "High Protein", "Meal Prep"],
    serves: 4,
    kcal: 520,
    protein: 42,
    carbs: 48,
    fats: 17,
    photoQuery: "ground turkey rice skillet",
    ingredients: [
      "500 g lean ground turkey",
      "1 cup dry jasmine rice",
      "1 can (400 g) black beans, drained",
      "1 cup corn kernels",
      "1 can (400 g) diced tomatoes",
      "1.5 cups low-sodium chicken broth",
      "1 tbsp olive oil",
      "2 tsp chili powder",
      "1 tsp ground cumin",
      "60 g shredded cheddar",
      "Fresh cilantro and lime to serve",
    ],
    directions: [
      "Heat the oil in a deep skillet and brown the turkey over medium-high heat, breaking it up as it cooks.",
      "Stir in the chili powder, cumin, and rice and toast for 1 minute.",
      "Add the beans, corn, tomatoes, and broth. Bring to a boil, then cover and simmer on low for 18 minutes until the rice is tender.",
      "Scatter the cheddar on top, cover for 2 minutes to melt, then finish with cilantro and lime.",
    ],
  },
  {
    id: "hp-cottage-pancakes",
    title: "Cottage Cheese Protein Pancakes",
    category: "High Protein",
    tags: ["Breakfast", "High Protein", "Under 500 Calories"],
    serves: 2,
    kcal: 330,
    protein: 28,
    carbs: 34,
    fats: 9,
    photoQuery: "protein pancakes berries",
    ingredients: [
      "1 cup cottage cheese",
      "2 large eggs",
      "3/4 cup rolled oats",
      "1 tsp vanilla extract",
      "1 tsp baking powder",
      "Pinch of cinnamon",
      "1 cup mixed berries to serve",
    ],
    directions: [
      "Blend the cottage cheese, eggs, oats, vanilla, baking powder, and cinnamon until smooth.",
      "Heat a nonstick pan over medium heat and lightly grease it.",
      "Pour small rounds of batter and cook 2 to 3 minutes per side until golden.",
      "Serve stacked with the berries on top.",
    ],
  },
  {
    id: "hp-steak-sweet-potato",
    title: "Sirloin Steak with Roasted Sweet Potato",
    category: "High Protein",
    tags: ["Dinner", "High Protein", "Gluten-Free"],
    serves: 2,
    kcal: 540,
    protein: 45,
    carbs: 38,
    fats: 22,
    photoQuery: "steak sweet potato dinner plate",
    ingredients: [
      "2 sirloin steaks (about 180 g each), trimmed",
      "2 medium sweet potatoes, cut into wedges",
      "2 cups broccoli florets",
      "1.5 tbsp olive oil",
      "1 tsp garlic powder",
      "1 tsp smoked paprika",
      "Salt and black pepper to taste",
    ],
    directions: [
      "Preheat the oven to 220C (425F). Toss the sweet potato wedges with half the oil, paprika, and salt, and roast for 25 minutes, adding the broccoli for the last 12.",
      "Pat the steaks dry and season generously with salt, pepper, and garlic powder.",
      "Sear in a hot pan with the remaining oil for 3 to 4 minutes per side for medium, then rest for 5 minutes.",
      "Slice the steak against the grain and plate with the wedges and broccoli.",
    ],
  },
  {
    id: "hp-tuna-white-bean",
    title: "Tuna and White Bean Power Salad",
    category: "High Protein",
    tags: ["Lunch", "High Protein", "No Cook", "Under 500 Calories"],
    serves: 2,
    kcal: 360,
    protein: 32,
    carbs: 28,
    fats: 13,
    photoQuery: "tuna white bean salad",
    ingredients: [
      "2 cans (145 g each) tuna in water, drained",
      "1 can (400 g) cannellini beans, drained and rinsed",
      "1 cup cherry tomatoes, halved",
      "2 celery stalks, sliced",
      "1/4 red onion, finely diced",
      "1 tbsp olive oil",
      "1 tbsp lemon juice",
      "1 tsp Dijon mustard",
      "2 big handfuls of arugula",
    ],
    directions: [
      "Whisk the olive oil, lemon juice, Dijon, and a pinch of salt into a dressing.",
      "Combine the tuna, beans, tomatoes, celery, and onion in a bowl.",
      "Toss with the dressing, then fold in the arugula just before serving.",
    ],
  },

  // ---------------------------------------------------------------- High Fiber
  {
    id: "hf-lentil-soup",
    title: "Hearty Red Lentil Soup",
    category: "High Fiber",
    tags: ["Lunch", "Vegan", "High Fiber", "Under 500 Calories"],
    serves: 4,
    kcal: 310,
    protein: 16,
    carbs: 46,
    fats: 7,
    photoQuery: "red lentil soup bowl",
    ingredients: [
      "1.5 cups dry red lentils, rinsed",
      "1 onion, diced",
      "2 carrots, diced",
      "2 celery stalks, diced",
      "3 garlic cloves, minced",
      "1 can (400 g) diced tomatoes",
      "5 cups vegetable broth",
      "1 tbsp olive oil",
      "1 tsp ground cumin",
      "1/2 tsp turmeric",
      "Lemon wedges to serve",
    ],
    directions: [
      "Heat the oil in a large pot and soften the onion, carrots, and celery for 6 minutes.",
      "Add the garlic, cumin, and turmeric and cook for 1 minute.",
      "Stir in the lentils, tomatoes, and broth. Bring to a boil, then simmer uncovered for 20 to 25 minutes until the lentils are soft.",
      "Season, blend half the soup for a creamier texture if you like, and serve with lemon wedges.",
    ],
  },
  {
    id: "hf-overnight-oats",
    title: "Raspberry Chia Overnight Oats",
    category: "High Fiber",
    tags: ["Breakfast", "Vegetarian", "High Fiber", "Under 500 Calories"],
    serves: 1,
    kcal: 390,
    protein: 17,
    carbs: 56,
    fats: 12,
    photoQuery: "overnight oats raspberry chia jar",
    ingredients: [
      "1/2 cup rolled oats",
      "1 tbsp chia seeds",
      "3/4 cup milk of choice",
      "1/2 cup Greek yogurt",
      "1 cup raspberries",
      "1 tsp honey or maple syrup",
      "1 tbsp almond butter",
    ],
    directions: [
      "Stir the oats, chia seeds, milk, yogurt, and honey together in a jar.",
      "Fold in half the raspberries, lightly crushing them.",
      "Cover and refrigerate overnight, or at least 4 hours.",
      "Top with the remaining raspberries and the almond butter before eating.",
    ],
  },
  {
    id: "hf-black-bean-tacos",
    title: "Smoky Black Bean and Avocado Tacos",
    category: "High Fiber",
    tags: ["Dinner", "Vegan", "High Fiber", "Under 500 Calories"],
    serves: 2,
    kcal: 450,
    protein: 15,
    carbs: 62,
    fats: 17,
    photoQuery: "black bean tacos avocado",
    ingredients: [
      "1 can (400 g) black beans, drained",
      "6 small corn tortillas",
      "1 avocado, sliced",
      "1 cup shredded red cabbage",
      "1/2 cup salsa",
      "1 tsp smoked paprika",
      "1/2 tsp ground cumin",
      "1 lime, cut into wedges",
      "Fresh cilantro to serve",
    ],
    directions: [
      "Warm the beans in a small pan with the paprika, cumin, a splash of water, and a pinch of salt, lightly mashing some of them.",
      "Char the tortillas in a dry pan for about 30 seconds per side.",
      "Fill each tortilla with beans, cabbage, avocado, and salsa.",
      "Finish with cilantro and a good squeeze of lime.",
    ],
  },
  {
    id: "hf-broccoli-quinoa-bake",
    title: "Cheesy Broccoli Quinoa Bake",
    category: "High Fiber",
    tags: ["Dinner", "Vegetarian", "High Fiber", "Meal Prep"],
    serves: 4,
    kcal: 380,
    protein: 19,
    carbs: 44,
    fats: 15,
    photoQuery: "broccoli quinoa casserole bake",
    ingredients: [
      "1 cup dry quinoa, rinsed",
      "4 cups small broccoli florets",
      "2 cups low-sodium vegetable broth",
      "1 cup milk",
      "100 g sharp cheddar, grated",
      "2 tbsp whole wheat flour",
      "1 tbsp olive oil",
      "1 garlic clove, minced",
      "Pinch of nutmeg",
    ],
    directions: [
      "Preheat the oven to 190C (375F). Cook the quinoa in the broth for 15 minutes, then fold in the broccoli.",
      "Warm the oil in a saucepan, stir in the flour and garlic for 1 minute, then whisk in the milk until it thickens.",
      "Off the heat, melt in most of the cheddar with the nutmeg, then combine the sauce with the quinoa and broccoli in a baking dish.",
      "Top with the remaining cheddar and bake for 20 minutes until bubbling and golden.",
    ],
  },

  // ---------------------------------------------------------------- Plant-Based
  {
    id: "pb-tofu-stirfry",
    title: "Crispy Tofu and Veggie Stir-Fry",
    category: "Plant-Based",
    tags: ["Dinner", "Vegan", "High Protein", "Under 500 Calories"],
    serves: 2,
    kcal: 430,
    protein: 26,
    carbs: 44,
    fats: 18,
    photoQuery: "crispy tofu stir fry vegetables",
    ingredients: [
      "400 g extra-firm tofu, pressed and cubed",
      "2 tbsp cornstarch",
      "1 tbsp sesame oil",
      "1 red bell pepper, sliced",
      "2 cups snap peas",
      "2 carrots, ribboned",
      "3 tbsp low-sodium soy sauce",
      "1 tbsp rice vinegar",
      "1 tsp maple syrup",
      "1 garlic clove and 1 tsp grated ginger",
      "1 cup cooked brown rice to serve",
    ],
    directions: [
      "Toss the tofu cubes in cornstarch and pan-fry in the sesame oil over medium-high heat until crisp on all sides, about 8 minutes. Set aside.",
      "Stir-fry the pepper, snap peas, and carrots for 3 to 4 minutes so they stay crisp.",
      "Whisk the soy sauce, vinegar, maple syrup, garlic, and ginger, pour it in, and return the tofu to the pan for 1 minute.",
      "Serve over the brown rice.",
    ],
  },
  {
    id: "pb-buddha-bowl",
    title: "Roasted Veggie Hummus Bowl",
    category: "Plant-Based",
    tags: ["Lunch", "Vegan", "High Fiber", "Under 500 Calories"],
    serves: 2,
    kcal: 460,
    protein: 15,
    carbs: 58,
    fats: 20,
    photoQuery: "buddha bowl roasted vegetables hummus",
    ingredients: [
      "1 cup cooked farro or brown rice",
      "1 zucchini, chopped",
      "1 red bell pepper, chopped",
      "1 cup cauliflower florets",
      "1 can (400 g) chickpeas, half for roasting",
      "1.5 tbsp olive oil",
      "1 tsp smoked paprika",
      "4 tbsp hummus",
      "Handful of baby spinach",
      "Lemon and tahini to drizzle",
    ],
    directions: [
      "Preheat the oven to 210C (410F). Toss the zucchini, pepper, cauliflower, and half the chickpeas with the oil and paprika.",
      "Roast for 22 to 25 minutes until browned at the edges.",
      "Build the bowls: grains and spinach at the base, roasted veggies and remaining chickpeas on top.",
      "Add a generous spoon of hummus and finish with lemon juice and a tahini drizzle.",
    ],
  },
  {
    id: "pb-pasta-primavera",
    title: "Creamy Cashew Pasta Primavera",
    category: "Plant-Based",
    tags: ["Dinner", "Vegan"],
    serves: 3,
    kcal: 510,
    protein: 18,
    carbs: 68,
    fats: 19,
    photoQuery: "vegan pasta primavera vegetables",
    ingredients: [
      "250 g whole wheat penne",
      "1/2 cup raw cashews, soaked 20 minutes in hot water",
      "1 cup unsweetened plant milk",
      "2 garlic cloves",
      "2 tbsp nutritional yeast",
      "1 cup asparagus pieces",
      "1 cup peas",
      "1 cup cherry tomatoes, halved",
      "1 tbsp olive oil",
      "Juice of 1/2 lemon",
    ],
    directions: [
      "Cook the penne per the package and reserve a cup of pasta water.",
      "Blend the drained cashews, plant milk, garlic, nutritional yeast, lemon juice, and a pinch of salt until completely smooth.",
      "Saute the asparagus in the oil for 3 minutes, then add the peas and tomatoes for 2 more.",
      "Toss the pasta with the sauce and vegetables, loosening with pasta water until silky.",
    ],
  },
  {
    id: "pb-lentil-bolognese",
    title: "Weeknight Lentil Bolognese",
    category: "Plant-Based",
    tags: ["Dinner", "Vegan", "High Fiber", "Meal Prep"],
    serves: 4,
    kcal: 440,
    protein: 20,
    carbs: 66,
    fats: 10,
    photoQuery: "lentil bolognese spaghetti",
    ingredients: [
      "300 g spaghetti",
      "1 cup dry brown or green lentils, rinsed",
      "1 onion, finely diced",
      "2 carrots, finely diced",
      "3 garlic cloves, minced",
      "2 cans (400 g each) crushed tomatoes",
      "2 cups vegetable broth",
      "1 tbsp olive oil",
      "1 tsp dried oregano",
      "1 tsp balsamic vinegar",
    ],
    directions: [
      "Soften the onion and carrots in the oil for 6 minutes, then add the garlic and oregano for 1 minute.",
      "Add the lentils, tomatoes, and broth. Simmer for 25 to 30 minutes until the lentils are tender, stirring now and then.",
      "Stir in the balsamic and season well.",
      "Cook the spaghetti, toss with the sauce, and serve.",
    ],
  },

  // ---------------------------------------------------------------- Pre-Workout
  {
    id: "pre-banana-toast",
    title: "Peanut Butter Banana Toast",
    category: "Pre-Workout",
    tags: ["Snack", "Quick Energy", "Under 500 Calories", "Vegetarian"],
    serves: 1,
    kcal: 340,
    protein: 11,
    carbs: 44,
    fats: 14,
    photoQuery: "peanut butter banana toast",
    ingredients: [
      "2 slices whole grain bread",
      "1.5 tbsp peanut butter",
      "1 banana, sliced",
      "1 tsp honey",
      "Pinch of cinnamon",
    ],
    directions: [
      "Toast the bread until golden.",
      "Spread with the peanut butter and lay the banana slices on top.",
      "Drizzle with honey, dust with cinnamon, and eat 60 to 90 minutes before training.",
    ],
  },
  {
    id: "pre-energy-smoothie",
    title: "Berry Oat Energy Smoothie",
    category: "Pre-Workout",
    tags: ["Snack", "Quick Energy", "Vegetarian", "Under 500 Calories"],
    serves: 1,
    kcal: 310,
    protein: 15,
    carbs: 52,
    fats: 6,
    photoQuery: "berry smoothie oats glass",
    ingredients: [
      "1 cup frozen mixed berries",
      "1/2 banana",
      "1/4 cup rolled oats",
      "3/4 cup milk of choice",
      "1/2 cup Greek yogurt",
      "1 tsp honey",
    ],
    directions: [
      "Add everything to a blender, liquids first.",
      "Blend until completely smooth, about 45 seconds.",
      "Drink 45 to 60 minutes before your session for steady energy.",
    ],
  },
  {
    id: "pre-rice-cakes",
    title: "Honey Ricotta Rice Cakes",
    category: "Pre-Workout",
    tags: ["Snack", "Quick Energy", "Vegetarian", "Under 500 Calories"],
    serves: 1,
    kcal: 260,
    protein: 12,
    carbs: 38,
    fats: 7,
    photoQuery: "rice cakes ricotta honey berries",
    ingredients: [
      "3 plain rice cakes",
      "1/3 cup ricotta cheese",
      "1 tsp honey",
      "1/2 cup sliced strawberries",
      "Pinch of cinnamon",
    ],
    directions: [
      "Spread the ricotta evenly over the rice cakes.",
      "Top with strawberries, drizzle with honey, and finish with cinnamon.",
      "Light and quick to digest, ideal 30 to 45 minutes before a lighter session.",
    ],
  },
  {
    id: "pre-datebites",
    title: "Almond Date Energy Bites",
    category: "Pre-Workout",
    tags: ["Snack", "Vegan", "Meal Prep", "Quick Energy"],
    serves: 6,
    kcal: 190,
    protein: 5,
    carbs: 26,
    fats: 8,
    photoQuery: "date energy balls oats",
    ingredients: [
      "12 Medjool dates, pitted",
      "1 cup rolled oats",
      "1/2 cup almonds",
      "2 tbsp almond butter",
      "1 tbsp chia seeds",
      "Pinch of sea salt",
    ],
    directions: [
      "Pulse the almonds and oats in a food processor until coarsely ground.",
      "Add the dates, almond butter, chia seeds, and salt and process until the mixture sticks together.",
      "Roll into 12 balls (2 per serving) and chill for 20 minutes.",
      "Keep refrigerated for up to a week; grab two on the way to a workout.",
    ],
  },

  // ---------------------------------------------------------------- Post-Workout
  {
    id: "post-chicken-rice",
    title: "Recovery Chicken and Rice Bowl",
    category: "Post-Workout",
    tags: ["Dinner", "High Protein", "Recovery"],
    serves: 2,
    kcal: 520,
    protein: 44,
    carbs: 56,
    fats: 12,
    photoQuery: "grilled chicken rice bowl vegetables",
    ingredients: [
      "2 chicken breasts (about 300 g)",
      "1 cup dry jasmine rice",
      "2 cups baby spinach",
      "1 cup shelled edamame",
      "1 carrot, ribboned",
      "2 tbsp teriyaki sauce",
      "1 tbsp olive oil",
      "Sesame seeds to finish",
    ],
    directions: [
      "Cook the rice per the package.",
      "Season the chicken, cook in the oil over medium heat for 6 to 7 minutes per side, then rest and slice.",
      "Warm the edamame and wilt the spinach in the same pan for 2 minutes.",
      "Build bowls with rice, spinach, edamame, carrot, and chicken. Drizzle with teriyaki and scatter sesame seeds.",
    ],
  },
  {
    id: "post-protein-smoothie",
    title: "Chocolate Recovery Shake",
    category: "Post-Workout",
    tags: ["Snack", "High Protein", "Recovery", "Under 500 Calories"],
    serves: 1,
    kcal: 380,
    protein: 34,
    carbs: 42,
    fats: 9,
    photoQuery: "chocolate protein shake banana",
    ingredients: [
      "1 scoop (30 g) chocolate protein powder",
      "1 banana",
      "1 cup milk of choice",
      "1 tbsp cocoa powder",
      "1 tbsp peanut butter",
      "Handful of ice",
    ],
    directions: [
      "Blend everything until smooth and creamy.",
      "Drink within 45 minutes of finishing your session to support muscle recovery.",
    ],
  },
  {
    id: "post-egg-scramble",
    title: "Veggie Egg White Scramble on Toast",
    category: "Post-Workout",
    tags: ["Breakfast", "High Protein", "Recovery", "Under 500 Calories"],
    serves: 1,
    kcal: 350,
    protein: 30,
    carbs: 34,
    fats: 11,
    photoQuery: "egg white scramble toast spinach",
    ingredients: [
      "2 large eggs plus 3 egg whites",
      "1 cup baby spinach",
      "1/2 cup cherry tomatoes, halved",
      "2 slices whole grain bread",
      "1 tsp olive oil",
      "Salt, pepper, and chives",
    ],
    directions: [
      "Whisk the eggs and egg whites with a pinch of salt.",
      "Warm the oil in a nonstick pan, soften the tomatoes for 2 minutes, then wilt the spinach.",
      "Pour in the eggs and scramble gently over medium-low heat until just set.",
      "Pile onto the toasted bread and finish with pepper and chives.",
    ],
  },
  {
    id: "post-yogurt-bowl",
    title: "Greek Yogurt Crunch Bowl",
    category: "Post-Workout",
    tags: ["Snack", "High Protein", "Recovery", "Under 500 Calories"],
    serves: 1,
    kcal: 320,
    protein: 25,
    carbs: 38,
    fats: 8,
    photoQuery: "greek yogurt granola berries bowl",
    ingredients: [
      "1 cup 0% Greek yogurt",
      "1/3 cup granola",
      "1/2 cup blueberries",
      "1 tsp honey",
      "1 tbsp pumpkin seeds",
    ],
    directions: [
      "Spoon the yogurt into a bowl.",
      "Top with granola, blueberries, and pumpkin seeds.",
      "Finish with the honey. Great within an hour after training.",
    ],
  },
];

export function getRecipe(id: string): Recipe | undefined {
  return RECIPES.find((r) => r.id === id);
}
